services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: factura-generator-api
    ports:
      - "8000:8000"
    networks:
      - factura-network
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: factura-generator-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
      - FLASK_ENV=production
      - PYTHONPATH=/app
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - factura-network
    restart: unless-stopped

networks:
  factura-network:
    driver: bridge
